[theme]
primaryColor = "#007acc"
backgroundColor = "#2b2b2b"
secondaryBackgroundColor = "#424242"
textColor = "#fafafa"
font = "sans serif"

[server]
enableStaticServing = true

[browser]
gatherUsageStats = false